CREATE TABLE DUMMYLOGS(
	ID SERIAL PRIMARY KEY NOT NULL,
	LOG_DATE timestamp NOT NULL,
	LOG_HOST TEXT NOT NULL,
	LOG_PROCESS TEXT ,
	LOG_MESSAGGE TEXT NOT NULL
);

CREATE TABLE APACHEDUMMYLOGS2(
	ID SERIAL PRIMARY KEY NOT NULL,
	LOG_CHI inet NOT NULL,
	LOG_SPACE TEXT NULL,
	LOG_CAUN TEXT NULL,
	LOG_CQTD timestamp NOT NULL,
	LOG_CQTX TEXT NOT NULL,
	LOG_PSSC INT NULL,
	LOG_PSCL INT NULL

);